name    'acme-profile_base'
version '0.2.2'
source 'https://github.com/RedHatEMEA/acme-soe'
author 'Nick Strugnell <nstrug@redhat.com>'
license 'GPL v3'
summary 'Base Profile class'
description 'A profile for a general purpose server'
project_page 'https://github.com/RedHatEMEA/acme-soe'

