name    'acme-profile_nfs'
version '0.1.0'
source 'https://github.com/RedHatEMEA/acme-soe'
author 'Nick Strugnell <nstrug@redhat.com>'
license 'GPL v3'
summary 'Simple NFS server and client configuration'
description 'Simple NFS server and client configuration'
project_page 'https://github.com/RedHatEMEA/acme-soe'

