name    'acme-role_www'
version '0.2.0'
source 'https://github.com/RedHatEMEA/acme-soe'
author 'Nick Strugnell <nstrug@redhat.com>'
license 'GPL v3'
summary 'Role class for a webserver'
description 'Include this class for a client in the webserver role'
project_page 'https://github.com/RedHatEMEA/acme-soe'

